version: '2'

services:
  #apiserver:
  #  image: registry.cn-hangzhou.aliyuncs.com/zanecloud/apiserver:1.0.0
  #  network_mode: bridge
  #  restart: always
  #  environment:
  #    - "ADDR=0.0.0.0"
  #    - "PORT=8080"
  #    - "MGO_DB=zanecloud"
  #    - "MGO_URLS=mongodb"
  #  links:
  #    - mgodb
  #  ports:
  #    - "8080:8080"
   mongodb:
     image: mongo:3.4.5
     network_mode: bridge
     restart: always
   apiserver:
     image: registry.cn-hangzhou.aliyuncs.com/zanecloud/apiserver:1.0.0
     restart: always
     network_mode: bridge
     command: -l debug start
     environment:
       - "ADDR=0.0.0.0"
       - "PORT=8080"
       - "MGO_DB=zanecloud"
       - "MGO_URLS=mongodb"
     links:
       - mongodb
     ports:
       - "8080:8080"

